name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Test
      run: go test -v ./...

    - name: Build Linux binary
      env:
        GOOS: linux
        GOARCH: amd64
      run: go build -v -o build/wirestat_linux_amd64 ./...

    - name: Build ARM binary
      env:
        GOOS: linux
        GOARCH: arm64
      run: go build -v -o build/wirestat_linux_arm64 ./...

    - name: Upload binaries
      uses: actions/upload-artifact@v3
      with:
        name: built-binaries
        path: build/wirestat*
